export default [
    {
        id:'1',
        header_img:require('./assets/logoFAHYellow.png'),
        title: 'First Slide',
        description:'Somos una organizacion sin animo de lucro que busca ayudar a las mascotas a encontrar un hogar',
        description_font_size:16,
        description_horizontal_padding:'10%',
        background_color:'#3A302E',
        color:'#D9D9D9',
    },
    {
        id:'2',
        header_img:require('./assets/logoFAHYellow.png'),
        title:'Second Slide',
        description: 'Podras adoptar a tu mascota sonada o encontrarle un mejor hogar a un gatito rescatado',
        description_font_size:16,
        description_horizontal_padding:'15%',
        background_color:'#AB4E68',
        color:'#D9D9D9',
        footer_image:require('./assets/animals.png'),
    },
    {
        id:'3',
        header_img:require('./assets/logoFAHPink.png'),
        title:'Third Slide',
        description:'No discriminamos por raza y priorizamos a los que mas tiempo llevan sin un hogar',
        description_font_size:16,
        description_horizontal_padding:'9%',
        background_color:'#FFC733',
        color:'#3A302E',
    },
    {
        id:'4',
        header_img:require('./assets/logoFAHYellow.png'),
        title:'Registrate',
        description:'Registrate',
        description_font_size:16,
        description_horizontal_padding:'10%',
        description_icon:require('./assets/googleIcon.png'),
        description_bottom_border_color:'#ACACAC',
        description_message:'Ingresar como invitado',
        description_message_color:'#ACACAC',
        background_color:'#3A302E',
        color:'#D9D9D9',
    }
]